version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  image: latest

python:
  version: 3.7
  system_packages: true 
  install:
     - requirements: docs/requirements.txt

formats: []

# end
