sudo: false
language: python

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

python:
  - "3.6"
  - "3.7"
before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install pytest-flake8 pytest-pep8 pytest-cov codecov astropy drizzlepac MarkupSafe astroscrappy

install:
  - python setup.py build

script: python setup.py test

after_success:
  - codecov --token=ad5c3413-acac-4481-86fa-f8ab47c7535e

