name: deepcr
channels:
  - conda-forge
  - anaconda
  - pytorch
  - defaults
dependencies:
  - astropy>=3.1.2
  - matplotlib>=3.0.3
  - numpy>=1.16.3
  - scikit-image>=0.15.0
  - scipy>=1.2.1
  - pytorch
  - pip:
    - drizzlepac
    - astroscrappy
